<?php
require_once (dirname(__FILE__) . '/includes/pdf.field.inc');

function pdf_menu() {
  $items = array();
  $items['pdf/worker_loader.js'] = array(
    'page callback' => 'pdf_worker_loader_js',
    'access callback' => TRUE,
  );
  $items['file/%/fullscreen'] = array(
    'page callback' => 'pdf_js_viewer',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );

  return $items;
}

function pdf_theme() {
  $path = drupal_get_path('module', 'pdf') . '/theme';

  $theme = array(
    'pdf_formatter_default' => array(
      'variables' => array('file' => NULL),
//      'file' => 'includes/media_pdf.theme.inc',
    ),
    'pdf_formatter_thumbnail' => array(
      'variables' => array('file' => NULL),
//      'file' => 'includes/media_pdf.theme.inc',
    ),
  );
  $theme['pdf_viewer'] = array(
    'template' => 'pdf-viewer',
    'variables' => array('file' => NULL),
    'path' => $path,
    //'file' => 'theme/pdf-viewer.tpl.php'
  );
  return $theme;
}

function pdf_worker_loader_js() {
  global $base_url;
//  $output = "'use strict';";
  $output = "importScripts('$base_url/sites/all/libraries/pdf.js/build/pdf.js');";
  print $output;
  exit();
}

function pdf_js_viewer($fid) {
  $file = file_load($fid);
  $file_url = file_create_url($file->uri);
  print theme('pdf_viewer', array('file' => $file_url));
  exit();
}
