<?php
/**
 * @file
 * Provides integration between Media file entity fields and the Colorbox module.
 */

/**
 * Implements hook_theme().
 */
function media_colorbox_theme() {
  return array(
    'media_colorbox' => array(
      'variables' => array(
        'item' => array(),
        'item_style' => NULL,
        'item_class' => NULL,
        'entity_id' => NULL,
        'field' => array(),
        'display_settings' => array(),
        'langcode' => NULL,
        'path' => NULL,
        'title' => NULL,
        'media_colorbox_caption' => NULL, //for file entity field based caption
      ),
      'path' => drupal_get_path('module', 'media_colorbox'),
      'file' => 'media_colorbox.theme.inc',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function media_colorbox_menu() {
  $items['media_colorbox/%file/%/%'] = array(
    'title' => 'Colorbox',
    'page callback' => 'media_colorbox_callback',
    'page arguments' => array(1, 2, 3),
    'access callback' => 'file_entity_access',
    'access arguments' => array('view'),
    'type' => MENU_CALLBACK,
    'file' => 'media_colorbox.pages.inc',
  );
  return $items;
}

/**
 * Implements hook_entity_info_alter().
 *
 * Add default Colorbox view mode to the file entity type as a simple starting point.
 */
function media_colorbox_entity_info_alter(&$entity_info) {
  $entity_info['file']['view modes']['colorbox'] = array('label' => t('Colorbox'), 'custom settings' => TRUE);
}


/**
 * Implements hook_field_formatter_info().
 */
function media_colorbox_field_formatter_info() {
  return array(
    'media_colorbox' => array(
      'label' => t('Media Colorbox'),
      'field types' => array('media', 'file', 'image'),
      'settings' => array(
        'file_view_mode' => 'small',
        'colorbox_view_mode' => 'large',
        'dimensions' => '500x400',
        'colorbox_gallery' => 'post',
        'colorbox_gallery_custom' => '',
        'colorbox_caption' => 'title',//for file entity field based caption
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function media_colorbox_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();
  $file_entity_manage = FALSE;

  if ($display['type'] == 'media_colorbox') {
    $entity_info = entity_get_info('file');
    $options = array('default' => t('Default'));
    foreach ($entity_info['view modes'] as $file_view_mode => $file_view_mode_info) {
      $options[$file_view_mode] = $file_view_mode_info['label'];
    }
    
    //if $field is not set, then managing File type file display
    //remove current view_mode as selecting current view mode as file view mode will cause fatal error
    if (!isset($field)) {
      $file_entity_manage = TRUE;
      unset($options[$view_mode]);
      //also need to unset any view mode already using the media_colorbox formatter
      foreach ($entity_info['view modes'] as $file_view_mode => $file_view_mode_info) {
        $display_name = $form['#file_type'] . '__' . $file_view_mode . '__file_field_media_colorbox';
        $result = ctools_export_load_object('file_display', 'names', array($display_name));
        //there will be a record in the file_display table if this view_mode has been configured to use Media Colorbox
        //the status will be 1 if the media_colorbox formatter is active for this view_mode
        if (isset($result[$display_name]) && $result[$display_name]->status == 1) {
          unset($options[$file_view_mode]);
        }
      }
    }

    $element['file_view_mode'] = array(
      '#title' => t('File view mode'),
      '#type' => 'select',
      '#default_value' => $settings['file_view_mode'],
      '#options' => $options,
    );
    $element['colorbox_view_mode'] = array(
      '#title' => t('Colorbox view mode'),
      '#type' => 'select',
      '#default_value' => $settings['colorbox_view_mode'],
      '#options' => $options,
    );
    //add description for File type manage file dispay form
    if ($file_entity_manage) {
      $element['file_view_mode']['#description'] = t('Only view modes not already using the Media Colorbox formatter');
      $element['colorbox_view_mode']['#description'] = t('Only view modes not already using the Media Colorbox formatter');
    }
    $element['dimensions'] = array(
      '#title' => t('Dimensions'),
      '#type' => 'textfield',
      '#default_value' => $settings['dimensions'],
      '#size' => 10,
    );
    $gallery = array(
      'post' => t('Per post gallery'),
      'page' => t('Per page gallery'),
      'field_post' => t('Per field in post gallery'),
      'field_page' => t('Per field in page gallery'),
      'custom' => t('Custom'),
      'none' => t('No gallery'),
    );
    $element['colorbox_gallery'] = array(
      '#title' => t('Gallery (image grouping)'),
      '#type' => 'select',
      '#default_value' => $settings['colorbox_gallery'],
      '#options' => $gallery,
      '#description' => t('How Colorbox should group the image galleries.'),
    );
    $element['colorbox_gallery_custom'] = array(
      '#title' => t('Custom gallery'),
      '#type' => 'machine_name',
      '#maxlength' => 32,
      '#default_value' => $settings['colorbox_gallery_custom'],
      '#description' => t('All images on a page with the same gallery value (rel attribute) will be grouped together. It must only contain lowercase letters, numbers, and underscores.'),
      '#required' => FALSE,
      '#machine_name' => array(
        'exists' => 'colorbox_gallery_exists',
        'error' => t('The custom gallery field must only contain lowercase letters, numbers, and underscores.'),
      ),
      '#states' => array(
        'visible' => array(
          ':input[name$="[settings_edit_form][settings][colorbox_gallery]"]' => array('value' => 'custom'),
        ),
      ),
    );
    //for file entity field based caption
    $caption = array(
      'title' => t('Title text'),
      'mediafield' => t('File Type text field'),
      'none' => t('None'),
    );
    $element['colorbox_caption'] = array(
      '#title' => t('Caption'),
      '#type' => 'select',
      '#default_value' => $settings['colorbox_caption'],
      '#options' => $caption,
      '#description' => t('Title will use the label of your Media field for this content type<br/>and File Type text field will use the value <br/>of a specified text field for the file type being displayed.'),
    );
  }

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function media_colorbox_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = array();

  if ($display['type'] == 'media_colorbox') {
    $entity_info = entity_get_info('file');
    $options = array('default' => t('Default'));
    foreach ($entity_info['view modes'] as $file_view_mode => $file_view_mode_info) {
      $options[$file_view_mode] = $file_view_mode_info['label'];
    }

    if (isset($options[$settings['file_view_mode']])) {
      $summary[] = t('File view mode: @style', array('@style' => $options[$settings['file_view_mode']]));
    }
    else {
      $summary[] = t('File view mode: none');
    }

    if (isset($options[$settings['colorbox_view_mode']])) {
      $summary[] = t('Colorbox view mode: @style', array('@style' => $options[$settings['colorbox_view_mode']]));
    }
    else {
      $summary[] = t('Colorbox view mode: none');
    }

    if (isset($settings['dimensions'])) {
      $summary[] = t('Dimensions: @dimensions', array('@dimensions' => $settings['dimensions']));
    }

    $gallery = array(
      'post' => t('Per post gallery'),
      'page' => t('Per page gallery'),
      'field_post' => t('Per field in post gallery'),
      'field_page' => t('Per field in page gallery'),
      'custom' => t('Custom'),
      'none' => t('No gallery'),
    );
    if (isset($settings['colorbox_gallery'])) {
      $summary[] = t('Colorbox gallery type: @type', array('@type' => $gallery[$settings['colorbox_gallery']])) . ($settings['colorbox_gallery'] == 'custom' ? ' (' . $settings['colorbox_gallery_custom'] . ')' : '');
    }
    //custom caption field
    $caption = array(
      'title' => t('Title text'),
      'mediafield' => t('File Type text field'),
      'none' => t('None'),
    );
    if (isset($settings['colorbox_caption'])) {
      $summary[] = t('Colorbox caption: @type', array('@type' => $caption[$settings['colorbox_caption']]));
    }
  }

  return implode('<br />', $summary);
}

/**
 * Implements hook_field_formatter_view().
 */
function media_colorbox_field_formatter_view($entity_type, $entity, $field, $instances = NULL, $langcode = NULL, $items = NULL, $display = NULL) {
  $element = array();

  //the $field won't be set if being formatted by file_entity_file_formatter_file_field_view
  if(!isset($field)) {//standalone entity
    $build = file_view((object) $items[0], $display['settings']['file_view_mode'], 0, $langcode);
    $colorbox_caption_var_name = 'media_colorbox_' . $build['#bundle'] . '_caption_field_name';
    $colorbox_caption_field_name = variable_get($colorbox_caption_var_name);
    $colorbox_field_caption_value = NULL;

    if (isset($build['#file']->{$colorbox_caption_field_name})){
      $colorbox_field_caption_value = isset($build['#file']->{$colorbox_caption_field_name}['und'][0]) ?
      $build['#file']->{$colorbox_caption_field_name}['und'][0]['value'] : NULL;
    }
    //get attributes for item to use on item and wrapping link
    $class = isset($items[0]['override']['class']) ? $items[0]['override']['class'] : NULL;
    $style = isset($items[0]['override']['style']) ? $items[0]['override']['style'] : NULL;
    $build['file']['#attributes']['class'] = $class;
    $build['file']['#attributes']['style'] = $style;
    
    //variable array for theme_media_colorbox
    $element[0] = array(
        '#theme' => 'media_colorbox',
        '#item' => $build['file'],
        '#item_class' => $class,
        '#item_style' => isset($items[0]['override']['style']) ? $items[0]['override']['style'] : NULL,
        '#entity_id' => $entity->fid,
        '#field' => $field,
        '#display_settings' => $display['settings'],
        '#langcode' => $langcode,
        '#path' => 'media_colorbox/' . $entity->fid . '/' . $display['settings']['colorbox_view_mode'] . '/' . $langcode,
        '#title' => isset($instances['label']) ? $instances['label'] : NULL,
        '#media_colorbox_caption' => $colorbox_field_caption_value,
      );
  }
  elseif ($display['type'] == 'media_colorbox') {//file field on another entity, $field is set
    list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);
  
    $files = array();
    foreach ($items as $delta => $item) {
      if (isset($item['file'])) {
        $files[$item['fid']] = $item['file'];
      }
      else {
        $files[$item['fid']] = (object) $item;
      }
    }
    $build = file_view_multiple($files, $display['settings']['file_view_mode'], 0, $langcode);

    foreach (element_children($build) as $fid) {
      $colorbox_caption_var_name = 'media_colorbox_' . $build[$fid]['#bundle'] . '_caption_field_name';
      $colorbox_caption_field_name = variable_get($colorbox_caption_var_name);
      $colorbox_field_caption_value = NULL;
      
      if (isset($build[$fid]['#file']->{$colorbox_caption_field_name})){
        $colorbox_field_caption_value = isset($build[$fid]['#file']->{$colorbox_caption_field_name}['und'][0]) ?
        $build[$fid]['#file']->{$colorbox_caption_field_name}['und'][0]['value'] : NULL;
      }
      
      $element[$fid] = array(
        '#theme' => 'media_colorbox',
        '#item' => $build[$fid]['file'],
        '#entity_id' => $id,
        '#field' => $field,
        '#display_settings' => $display['settings'],
        '#langcode' => $langcode,
        '#path' => 'media_colorbox/' . $fid . '/' . $display['settings']['colorbox_view_mode'] . '/' . $langcode,
        //this is where Media is being added as the title attribute
        '#title' => isset($instances['label']) ? $instances['label'] : NULL,
        '#media_colorbox_caption' => $colorbox_field_caption_value,
      );
    }
  }
  return $element;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function media_colorbox_form_field_ui_field_edit_form_alter(&$form, &$form_state) {
  //only want this option to appear for text fields on file entities
  if ($form['#instance']['entity_type'] == 'file' && ($form['#instance']['widget']['type'] == 'text_textfield' || $form['#instance']['widget']['type'] == 'text_long')) {
    $instance = $form['instance'];
    $entity_type = $instance['entity_type']['#value'];
    $entity_info = entity_get_info($entity_type);
    $bundle = $instance['bundle']['#value'];
    $bundle_label = $entity_info['bundles'][$bundle]['label'];

    // Create the fieldset tab.
    $form['media_colorbox'] = array(
      '#type'   => 'fieldset',
      '#title'  => t('Colorbox Caption Field'),
      '#description' => t('Set field to be used as the Colorbox caption.
        Note: Selecting this text field as the Colorbox caption field will replace an previously checked field for this file type.'),
      '#tree'   => TRUE,
    );

    $form['media_colorbox']['caption_field'] = array(
      '#type' => 'checkbox',
      '#title' => t('Use field as Colorbox caption'),
    );

    //check to see if the colorbox file caption field is already set,
    //and if it is set to a different field than the current one
    if (isset($current_media_colorbox_caption_field_name)
      && $current_media_colorbox_caption_field_name !== $form['#instance']['field_name']) {
      $form['media_colorbox']['override_text'] = array(
        '#markup' => t('The @bundle file type is currently using the @field field as the Colorbox caption field,
        checking it for this field will override that value.',
          array('@bundle' => $bundle_label, '@field' => $current_media_colorbox_caption_field_name)),
      );
    }

    //additional submit function to process the caption_field checkbox value
    $form['#submit'] = array_merge($form['#submit'], array('media_colorbox_form_field_ui_field_edit_form_submit'));
  }
}

/**
 * Custom submit handler for the field_ui_field_edit_form altered form.
 */
function media_colorbox_form_field_ui_field_edit_form_submit($form, &$form_state) {
  if ($form['media_colorbox']['caption_field']) {
    $bundle = $form['instance']['bundle']['#value'];
    variable_set('media_colorbox_' . $bundle . '_caption_field_name', $form['#field']['field_name']);
  }
}
